#!/bin/sh
set -e

export AWS_ACCESS_KEY_ID=$PLUGIN_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$PLUGIN_SECRET_KEY
export AWS_DEFAULT_REGION=$PLUGIN_REGION

/root/.local/bin/aws $PLUGIN_CMD $PLUGIN_SUB_CMD
